### ISSUE TITLE
`auth_key` and `password` are both set

### ISSUE THREAD

**Issue by galvarado** [lucidfrontier45/RethinkPool#1]
I am presenting this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rethinkpool/**init**.py", line 104, in get_resource
    conn = connect_to_rethinkdb(self._connection_info)
  File "/usr/local/lib/python2.7/dist-packages/rethinkpool/__init__.py", line 49, in connect_to_rethinkdb
    info["timeout"], info["ssl"], *_info["other"]
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 655, in connect
    conn = connection_type(host, port, db, auth_key, user, password, timeout, ssl, _handshake_version, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 640, in **init**
    Connection.**init**(self, ConnectionInstance, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 544, in **init**
    raise ReqlDriverError("`auth_key` and `password` are both set.")
rethinkdb.errors.ReqlDriverError: `auth_key` and `password` are both set.

Using this options:

> > > pool = RethinkPool(host=configuration.RDB_HOST, port=configuration.RDB_PORT, auth_key=configuration.RDB_AUTH_KEY, ssl={'ca_certs': '../certificates/composecert'})

Since I am  using Rethindb Proxy, auth_key is the password itself, maybe without using auth_key the error is not present but this is solved changing password=None in the constructor like this:

```
def __init__(self, max_conns=10, initial_conns=0, get_timeout=10,
             host='localhost', port=r.DEFAULT_PORT, db=None,
             auth_key=None, user="admin", password=None,
             timeout=20, ssl=dict(), reconnect_interval=20, **kwargs):
```

**Comment by lucidfrontier45** [comment]
The `connect` function of the latest official python driver looks like this

```
def connect(host=None, port=None, db=None, auth_key=None, user=None, password=None, timeout=20, ssl=None, _handshake_version=10, **kwargs):
```

I think I can just follow this signiture.

**Comment by guillermo-sentinella** [comment]
Yep, that´s the best approach

**Comment by lucidfrontier45** [comment]
I merged connection params to `kwds` and implicitly pass them to the `r.connect` function like this.

``` python
class RethinkPool(object):

    def __init__(self, max_conns=10, initial_conns=0, get_timeout=10,
                 reconnect_interval=20, **kwds):
        """
        :param max_conns: maximum number of connections
        :param initial_conns: number of connections to be initially establish
        :param get_timeout: timeout for obtaining a connection from the queue
        :param host, port, ...: same as r.connect
        """

        self._current_conns = 0
        self.reconnect_interval = reconnect_interval
        self.get_timeout = get_timeout

        self._connection_info = kwds

        self._queue = Queue(max_conns)
        for _ in range(min(max_conns, min(initial_conns, max_conns))):
            self._queue.put(self._create_connection())

    def _create_connection(self):
        conn = r.connect(**self._connection_info)
        self._current_conns += 1
        return conn
```

@galvarado Could you try the latest master branch? If problem is solved, I'll register to PyPI
